### ISSUE TITLE
Blur disappears

### ISSUE THREAD

**Issue by Mystic8b** [felixse/FluentTerminal#782] opened 2020-06-05 15:13 UTC
Firstly - at first glance this is the best terminal of the existing ones, thanks!
All in all I like everything but one point - the blur disappears when the focus is lost (when I switch to another window, for example). This is exactly solvable, because the microsoft terminal solved this problem (although at first it was said that this was a feature of the system).
If you can do something about it, it will be incredibly cool!

**Comment by felixse** [comment] 2020-06-06 20:49
Duplicate of #640

**Closed by felixse** 2020-06-06 20:49 UTC
