### ISSUE TITLE
emoji didn't show properly

### ISSUE THREAD

**Issue by skycity233** [felixse/FluentTerminal#632] opened 2019-12-17 07:02 UTC
Fluent Terminal:
![](https://i.loli.net/2019/12/17/GqMHx3KTFnW2be8.png)

Windows Terminal:
<img src="https://i.loli.net/2019/12/17/Z8R2Vwu9QksrxSh.png"/>

**Comment by BasixKOR** [comment] 2020-01-10 10:19
Duplicate of #553.

**Closed** 2020-01-12 10:56 UTC
