### ISSUE TITLE
Can't type tilde (~) in terminal.

### ISSUE THREAD

**Issue by mkprogz** [felixse/FluentTerminal#895] opened 2021-02-23 07:59 UTC
I can't type tilde **(~)** in terminal. When i press **"SHIFT + ~"** i get "**À**" character. Polish layout keyboard. Every other characters are fine.

**Comment by pbousquets** [comment] 2021-02-24 14:34
AltGr+4 combination for tilde in Spanish keyboard neither unless I type the 'space' key afterwards.

**Comment by felixse** [comment] 2021-03-06 12:07
duplicate of #857

**Closed by felixse** 2021-03-06 12:07 UTC
