### ISSUE TITLE
xterm-256/24-bit colors are not supported

### ISSUE THREAD

**Issue by nta** [felixse/FluentTerminal#9] opened 2018-02-16 19:43 UTC
The terminal does not seem able to display extended (256-color/24-bit) terminal color sequences, instead displaying a lot of escape codes.

**Comment by felixse** [comment] 2018-02-16 20:39
Hi,
can you tell me which shell you experience this with?

**Comment by felixse** [comment] 2018-02-17 11:03
So apparently the problem is that winpty does not support 256 colors: https://github.com/rprichard/winpty/issues/108
Don't see any chance to fix this in the foreseeable future 😕

**Comment by skipmeister123** [comment] 2018-05-31 19:22
Is this why my vim colors don't show up properly?
![capture](https://user-images.githubusercontent.com/1911919/40803326-5cbab04e-64e6-11e8-8d7a-f6814ce4beac.PNG)

**Comment by felixse** [comment] 2018-05-31 19:43
Yes, exactly.
Microsoft is currently working on an official alternative for winpty (https://github.com/Microsoft/console/issues/57) that might support this, but I have no idea when this will be released

**Comment by Riebart** [comment] 2018-08-18 07:33
Quick update: https://github.com/Microsoft/console/issues/57 is officially closed, that TTY API is coming in the fall release of Windows 10.

**Closed** 2019-03-28 06:07 UTC
Labels: upstream

**Comment by Jaykul** [comment] 2019-03-28 22:05
@felixse is this closed because it's fixed now? Because I downloaded 0.4.1 yesterday, and was just about to file this as a bug 😉 (thanks to [node-pty 0.8](https://github.com/Microsoft/node-pty/releases/tag/0.8.0) VS Code fixed this awhile ago, and Hyper got this fixed in their canary builds, so I was expecting to see it would work here too ...

**Comment by Riebart** [comment] 2019-03-29 04:19
This works on Windows 10 1809 when not using winpty as the console backend. So give that a whirl and see if it is still an issue.

**Comment by Jaykul** [comment] 2019-03-29 19:30
That's weird. I'm happy to open a new issue to discuss this, but isn't WinPTY meant to be the new hotness? How is it working without that, but not with!?

**Comment by Riebart** [comment] 2019-03-30 02:49
ConPTY is the new wrapper provided by the Windows kernel starting in 1809. WinPTY was the previous third party wrapper, and while may grow to support ConPTY, for our needs using ConPTY is supported directly by FluentTerminal.

**Comment by Jaykul** [comment] 2019-03-30 20:45
Seems like that checkbox should be **off** by default, then.

**Comment by Riebart** [comment] 2019-03-30 22:52
My understanding is that ConPTY support is still experimental in FluentTerminal, hence why it isn't the default.

**Comment by horseinthesky** [comment] 2019-05-16 14:18
I really don't know what WinPTY and ConPTY are. What is the reason of my nvim in SecureCRT looks like this
<img width="334" alt="Screenshot_1" src="https://user-images.githubusercontent.com/19948672/57860975-79c71700-77fe-11e9-9ef7-b2777da88a37.png">

And nvim in FluentTerminal like this?
<img width="293" alt="Screenshot_2" src="https://user-images.githubusercontent.com/19948672/57860998-85b2d900-77fe-11e9-8557-8bfebd9c95b0.png">

Can it be fixed?
