### ISSUE TITLE
Font Ligature Support

### ISSUE THREAD

**Issue by KryskZ09** [felixse/FluentTerminal#806] opened 2020-06-24 06:46 UTC
Many editors have support for Font Ligatures, the most common one being Visual Studio Code w/ Fira Code.
Having an option for FT to use Font Ligatures would be amazing, or optionally allow a theme to use ligatures.

**Comment by felixse** [comment] 2020-06-28 14:10
Duplicate of #72

**Closed by felixse** 2020-06-28 14:10 UTC
