### ISSUE TITLE
the program does not work properly!!( Settings )

### ISSUE THREAD

**Issue by Phoenix1112** [felixse/FluentTerminal#873] opened 2020-11-27 12:06 UTC
hello. thanks for this project. I enter the settings section once and i turn off the settings option. Now I enter the settings section for the second time, but this time when the settings section is opened, the terminal shuts down automatically. terminal disappears on the desktop. 

https://www.youtube.com/watch?v=j_xiLh_fsaY

Another problem is that when I view the list of url addresses on the terminal, I cannot copy some of all url addresses. Because I can't select url addresses from the left and go down. When I do this, I accidentally click on a url and the web browser opens and displays the url.The terminal also needs to detect all url addresses as text. When we click, the web browser should not open.

https://www.youtube.com/watch?v=A4FdmmMGIUo

**Comment by Phoenix1112** [comment] 2020-11-27 14:32
hello.. i have new problem.. i can not write this characakter  ~ 

~ <this charachter working with alt + u  ... but flueant terminal showing this character  Y

**Comment by felixse** [comment] 2021-03-06 12:07
duplicate of #857

**Closed by felixse** 2021-03-06 12:07 UTC
