### ISSUE TITLE
Active tab color issue

### ISSUE THREAD

**Issue by AkazaRenn** [felixse/FluentTerminal#690] opened 2020-03-31 13:26 UTC
Current state is that the active tab is highlighted, making its color different from anywhere else like:
![image](https://user-images.githubusercontent.com/8340896/78031427-8a5a8000-7331-11ea-8b85-af27e851bb61.png)

I think the actual look needs to be like [Notepads](https://github.com/JasonStein/Notepads) or the Edge in which the active tab is connected with its content, and other tabs use another color like:
![image](https://user-images.githubusercontent.com/8340896/78031389-7c0c6400-7331-11ea-85dd-e7c15673785c.png)

This way is more descriptive that this tab is in the same "layer" with its content.

**Comment by felixse** [comment] 2020-03-31 18:04
Yeah, I totally agree here, just didn't get to rework this yet.
Closing this since it's a duplicate of #44

**Closed by felixse** 2020-03-31 18:04 UTC
