### ISSUE TITLE
[BUG?] Black Window On Inactive/Focus Out

### ISSUE THREAD

**Issue by angelhdz** [felixse/FluentTerminal#864] opened 2020-11-06 00:45 UTC
I have my window in a nice transparent color, but when the window loses focus, it turns all black. 
Can this be modified in the settings or is it a bug?

Thanks!

**Focus**
![image](https://user-images.githubusercontent.com/10191085/98312039-38ed3000-1fa7-11eb-8892-08b2f16ccee3.png)

**No Focus**

![image](https://user-images.githubusercontent.com/10191085/98312060-44405b80-1fa7-11eb-89a6-3e48d83ff745.png)

**Comment by hanskokx** [comment] 2020-11-06 01:23
Sadly, it's a Windows thing.

**Comment by felixse** [comment] 2020-11-08 21:50
duplicate of #30

**Closed by felixse** 2020-11-08 21:50 UTC
