### ISSUE TITLE
Add split screen

### ISSUE THREAD

**Issue by gunter423** [felixse/FluentTerminal#831] opened 2020-08-15 03:52 UTC
Hi, i have a question, is it possible to add a split screen ? (check screenshot)
![maxresdefault](https://user-images.githubusercontent.com/24797165/90304792-7451f400-debb-11ea-85e9-a8a3d597f863.jpg)

Have a nice day ;)

**Comment by kennymckormick** [comment] 2020-09-08 06:27
+1, that would be a cool and useful feature

**Comment by DavidDreher** [comment] 2020-09-21 07:56
Typically the better place to create such a layout would be in a multiplexer like tmux or screen then in the terminal emulator itself.

**Comment by gunter423** [comment] 2020-09-21 08:00
> Typically the better place to create such a layout would be in a multiplexer like tmux or screen then in the terminal emulator itself.

Tmux is availabe on Windows?

**Comment by PadreSVK** [comment] 2020-11-07 15:43
Duplicate of #501

**Closed** 2022-04-17 10:29 UTC
