### ISSUE TITLE
This is pretty much a nightmare for non-Windows developers!

### ISSUE THREAD

**Issue by RichardBronosky** [felixse/FluentTerminal#82] opened 2018-09-21 22:13 UTC
I don't think I'm alone in this because of WSL. There are going to be a lot of people thinking maybe they can try Windows, but there is no decent terminal. Seriously, none. But here is what a Linux or Mac refuge is going to experience:

First:
`git clone https://github.com/felixse/FluentTerminal.git`

Then follow...
https://github.com/felixse/FluentTerminal#how-to-install
Hmmm, `find . -name '*cer'` and `find . -name '*appx*'` reveal nothing.

Okay, follow...
https://github.com/felixse/FluentTerminal#how-to-build
* `choco install nodejs` works
* `choco install VisualStudio2017Community` works
* Developer Mode enabled

On to...
https://github.com/felixse/FluentTerminal#visual-studio-2017-configuration
* Uh, "Under Workloads"? Wat?
* "Under individual components"? Wat?
* Maybe I'll just try to open the FluentTerminal.sln file...
![screenshot_15](https://user-images.githubusercontent.com/13620/45908087-b86c1500-bdc8-11e8-8b90-2dcc5f263669.png)
* Ok, I guess...
![screenshot_16](https://user-images.githubusercontent.com/13620/45908118-d2a5f300-bdc8-11e8-9d8d-0b371782a4ff.png)
* Oh, good. It's going to install them for me...
![screenshot_17](https://user-images.githubusercontent.com/13620/45908144-03862800-bdc9-11e8-9551-3c1ccebcb40a.png)
* Wat?

Hmmm... Maybe the new MacBook Pro isn't as terrible as I thought.

Hey, it's your project and you are free to do it however you want. I just know that as the maintainer of many projects myself, I always wonder what the experience is like for people not on the inside. I'd love feedback like this on https://github.com/RichardBronosky/pi-init2 and I go and give presentations and hands-on workshops at [Meetups](https://www.meetup.com/Decatur-Makers/events/llsgmnyxkbmb/) to get it.

**Comment by skipmeister123** [comment] 2018-09-21 22:15
Why not just download the latest release off the releases page? 🤔
--
Hans Kokx

**Comment by RichardBronosky** [comment] 2018-09-21 22:31
Also, this is what I get when I open the `.cer` and allow it to "Automatically select the certificate store...". I would suggest some additional instruction here too.
![screenshot_18](https://user-images.githubusercontent.com/13620/45908838-970d2800-bdcc-11e8-806d-220d48b720c4.png)

**Comment by benplm** [comment] 2018-09-23 08:59
You're not reading the README: https://github.com/felixse/FluentTerminal#how-to-install
First install the certificate, then install the app.

**Comment by RichardBronosky** [comment] 2018-09-24 02:38
@benplm Yes, I figured that out. I'm suggesting that your README should be more clear for people not familiar with Windows. I imagine that you would expect that most people who would use a product like this are the more advanced users and you can assume a lot of base experience. However, WSL is attracting a new audience of **highly technical** people... with little to no recent Windows experience. This is a very strange and frustrating position for these people, but also for project owners having to deal with their needs. This post is intended to help you with that.

I made 2 suggestions for ways to improve the README. Seems a bit overkill to fork and pull request for that, but I can if you'd like.

**Comment by felixse** [comment] 2018-09-24 06:08
Thanks for your feedback @RichardBronosky. I will make some additions to the README to address the issues you had with installing. 

This is all pretty much in beta right now, in the end this should be either available in Microsoft Store or we create an installer.

**Comment by Riebart** [comment] 2018-09-28 01:17
Until this makes it into the Microsoft Store, this should be considered beta niche software. While I'm sensitive to your concerns, UWP apps are either a massive pain in the ***, or dead simple, depending on whether or not they are in the store. Like iOS apps, and putting an iPhone into developer mode.

That said, since your profile says you love automating hard stuff, we welcome any PRs that automate the installation process. 😸 

I've made PR #83 for documentation clarifications so I recommend that specific changes be suggested on the PR's thread.

**Comment by felixse** [comment] 2018-10-05 08:57
I merged this for now, we can make another update if we find additional points. Thanks for your great help @Riebart

**Comment by RichardBronosky** [comment] 2018-10-05 20:20
This is great stuff. Thanks, all. I know you consider this _niche software_, and it probably is to life-long Windows folk. However, the perfect storm of the new Mac hardware sucking and WSL making Windows finally usable by web professionals is making _this niche_ very desirable. Mac and Linux folk are used to having great terminals and there just isn't one for Windows. We are clamoring for it.

**Comment by justingallagher** [comment] 2018-10-07 21:15
I'm willing to take a shot at scripting this. The good news is that the included `Add-AppDevPackage.ps1` does most of what we want already. The problem is that it requires a developer license, so it doesn't work if you're in sideload mode.

The side benefit is that we could also integrate the explorer context menu addition into the install.

**Closed** 2019-01-31 21:47 UTC
