### ISSUE TITLE
Enhancement: Rename Tab

### ISSUE THREAD

**Issue by ChristianSauer** [felixse/FluentTerminal#154] opened 2018-12-17 08:41 UTC
It would be great if you could rename a tab (e.g. on right click). E.g. you have a console with a ssh connection open and want to name that tabe like the server name.

**Comment by skipmeister123** [comment] 2018-12-17 14:39
I had this thought too, but it was suggested that you can rename the tab 
via environment variables. That's how I handle it now.
--
Hans Kokx

**Comment by ChristianSauer** [comment] 2018-12-18 13:22
@skipmeister123  Do you have any idea how the env variable is named?

**Comment by rafd123** [comment] 2018-12-18 14:44
Here's how I do it.

**cmd.exe**
```
title foo
```

**PowerShell**
```
[console]::Title = 'foo'
```

**bash/WSL**
```
echo -e '\033]2;foo\007'
```

**Comment by rafd123** [comment] 2018-12-19 21:32
FWIW, I think this is a duplicate of https://github.com/felixse/FluentTerminal/issues/141

**Comment by skipmeister123** [comment] 2018-12-19 21:33
Agreed.
--
Hans Kokx

**Comment by ChristianSauer** [comment] 2019-01-06 19:46
I realized the last few days that I am often unable to set the name of the shell via a command inside said shell, because I am running something blocking which prevents me to use the rename functionality.
E.g. runnign ssh xyz in powershell changes the prompt name  - so renmaing through a button would be great.

**Closed** 2019-01-07 21:35 UTC
Labels: enhancement
