### ISSUE TITLE
Wrong/Confusing Keybindings?

### ISSUE THREAD

**Issue by flashmaster77** [felixse/FluentTerminal#705] opened 2020-04-08 00:27 UTC
Hi, i just started using Fluent Terminal as replacement for Powershell and i quite like it. But what bothers me is that i cant type the '@' character, which is on 'Q' on the german qwertz layout, because ALTGR + Q opens new Quicklaunch Tab. Is there a way to remove or change that binding?

**Comment by felixse** [comment] 2020-04-08 06:02
duplicate of #699, will be fixed with the next update

**Comment by felixse** [comment] 2020-04-08 06:03
Also you can edit keybindings in the settings meanwhile

**Closed by felixse** 2020-04-08 06:02 UTC
