### ISSUE TITLE
Two profiles with same executable does not work

### ISSUE THREAD

**Issue by prochnowc** [felixse/FluentTerminal#321] opened 2019-04-15 05:51 UTC
I have two profiles which point to the same executable but with different command line arguments and keyboard shortcut.
Unfortunately when I press the shortcut of the second profile the first profile is launched.

**Comment by felixse** [comment] 2019-08-31 12:43
duplicate of #474 (solved now)

**Closed by felixse** 2019-08-31 12:43 UTC
