### ISSUE TITLE
Terminal scrollback doesn't work well with tmux

### ISSUE THREAD

**Issue by AVSurfer123** [felixse/FluentTerminal#799] opened 2020-06-16 18:03 UTC
Hello, I'm trying to use tmux inside the terminal windows and am setting the mouse option on with `set -g mouse on`.  However, it seems like the Fluent Terminal takes priority of the mouse wheel and scrolls the entire screen back, instead of just the current pane in tmux. Example here:
![image](https://user-images.githubusercontent.com/10717018/84810966-1fd4ea00-afda-11ea-82ed-36f8db2628c8.png). Could this be fixed? Thanks

**Comment by felixse** [comment] 2020-06-28 14:18
Duplicate of #50

**Closed by felixse** 2020-06-28 14:18 UTC
