### ISSUE TITLE
enhancement: Start elevated Shells

### ISSUE THREAD

**Issue by paradonym** [felixse/FluentTerminal#274] opened 2019-03-30 15:37 UTC
as far as I can see it's not possible to start FluentTerminal with the Start menu as an elevated user. 
If I add arguments like "-Verb runas" to the Powershell Profile the window won't start...

Is it possible to add an "elevated" option for the profiles, to have an elevated CMD and PowerShell or WSL started as root upon starting FluentTerminal?

**Comment by ericcornelissen** [comment] 2019-04-01 14:48
If by "an elevated CMD and PowerShell" you mean _Run as administrator_ then you can follow the discussion #6 🙂 

As for root in WSL, I don't know if that is possible but I think it also belongs in that thread 🤔

**Comment by elangelo** [comment] 2019-04-01 16:16
the one ine #6 is not working for me... it opens up a new window with powershell, as admin.

**Comment by paradonym** [comment] 2019-04-01 17:35
That's what I meant. Having an admin shell in fluentterminal is better.
Sudoing things may work, but isn't that beautiful than fluentterminal
because of the new windows.

Having a wsl as root may be possible with starting commands and hiding the
output of them. So you could execute "sudo su" and the password entry
before the output starts.
Which involves saving a root password. Which isn't ideal.

Samuel Verstraete <notifications@github.com> schrieb am Mo., 1. Apr. 2019,
18:16:

**Comment by felixse** [comment] 2019-04-02 05:53
https://stefanwick.com/2018/10/06/app-elevation-samples-part-2/
We might be able to pull this off, but only for Windows 1809+ (we need both ConPTY and a new capability)

**Comment by Ronkiro** [comment] 2020-01-09 12:58
> the one ine #6 is not working for me... it opens up a new window with powershell, as admin.

You might be using the wrong sudo. choco's sudo work this way. You should uninstall the sudo installed from choco (And remove it from PATH) and then install Scoop's sudo.

**Comment by felixse** [comment] 2020-02-29 12:37
Duplicate of #6

**Closed by felixse** 2020-02-29 12:37 UTC
