### ISSUE TITLE
Cascadia Code LP

### ISSUE THREAD

**Issue by HansBuddenbergBlamey** [felixse/FluentTerminal#800] opened 2020-06-16 20:20 UTC
The font Cascadia Code LP not work.

**Comment by skipmeister123** [comment] 2020-06-16 21:27
Can you provide additional details? A screenshot of the issue, perhaps?

**Comment by spaceaardvark** [comment] 2020-08-25 21:09
Cascadia Code has font ligatures. This is a duplicate of #72. You can still use Cascadia *Mono*, though, which does not have ligatures.

**Closed** 2020-11-08 21:57 UTC
