### ISSUE TITLE
Memory issues

### ISSUE THREAD

**Issue by spurll** [felixse/FluentTerminal#75] opened 2018-08-29 14:13 UTC
I've noticed a couple times that FluentTerminal seems to be a bit of a memory hog, but this morning I came in to find it using 9.5 GiB of memory and significant disk activity even though it was (in theory) idle.

I'd left my computer locked overnight and it was basically unresponsive until I ended the task. I couldn't get FluentTerminal to do anything (even close). FluentTerminal only had two tabs open, both of which were PowerShell (one of which was also running WSL bash). Other than bash, neither was running any other processes: both were sitting at command prompts.

![image](https://user-images.githubusercontent.com/3604963/44793212-5de5ed00-ab6b-11e8-87ac-df73a4bef2d7.png)

I haven't taken a close look at the FluentTerminal code, but this sounds like a memory leak. Reopening FluentTerminal and the two tabs results in 200 MiB of memory and disk access that sits at zero.

It's possible that it's an underlying issue with WSL or PowerShell, but I don't remember encountering these issues when I was running Cmdr/ConEmu.

Built from source 11 days ago, commit eecc2e8243b6066db756c359cb656f7ff5d82fb7.

**Comment by felixse** [comment] 2018-08-29 19:10
Wow, that's an awful lot. Can you [expand the process group](https://user-images.githubusercontent.com/30559812/44809688-bbac2080-abcf-11e8-8a13-0d7dfb8548a0.png) the next time you experience this? Just to make sure it's not something in conhost/powershell/winpty or maybe the SystemTray process.

**Comment by spurll** [comment] 2018-08-29 19:49
Yeah, I'll do that next time this comes up.

**Comment by skipmeister123** [comment] 2018-08-29 19:50
I'll try to reproduce this when I get a chance.
--
Hans Kokx

**Comment by spurll** [comment] 2018-08-30 14:17
Update: About an hour after I unlocked my machine this morning, I took a look at Task Manager. I had not touched FluentTerminal at all since last night, and it looked like this:

![image](https://user-images.githubusercontent.com/3604963/44856960-56d6e180-ac34-11e8-9576-125115a874ee.png)

Weirdly, as soon as I foregrounded FluentTerminal, memory usage shot **way down** (but it was completely unresponsive):

![image](https://user-images.githubusercontent.com/3604963/44857425-64d93200-ac35-11e8-87c5-62dc9a56eb80.png)

Same setup as before: two tabs, one with PowerShell, another with PowerShell running WSL bash.

**Comment by felixse** [comment] 2018-08-31 05:35
Ok, I will attach it to a profiler this weekend.
 It would be interesting to see whether [Version 0.1.11.0](https://github.com/felixse/FluentTerminal/releases/tag/0.1.11.0) shows the same behaviour (the one before we started with AppServiceConnection for IPC)

**Comment by Riebart** [comment] 2018-10-02 02:12
So in some quick testing for an unrelated reason, I've noticed that each new tab consumes 20-50MB of memory that is not released when the tab is closed (looks like about 50MB on tab opening, and about 30MB is released when the tab is closed). So workflows that use short-lived tabs are going to end up consuming a great deal of memory over their lifespan.

**Comment by felixse** [comment] 2018-10-02 05:55
I wouldn't expect it to be released immediately, since .NET is using a garbage collector. But in general this needs more investigation, I agree.

**Comment by Riebart** [comment] 2018-10-02 15:12
So I am testing with a release build installed as an app (the above numbers were with a debug build running under Visual Studio), and it holds onto it indefinitely it seems. About 10-15MB per closed tab, it's held onto it for over an hour so far.

**Comment by spurll** [comment] 2018-10-04 14:18
FWIW, I can confirm that I'm not opening/closing lots of tabs. (Maybe one new tab opened/closed per day.) Just got the issue again this morning (for the first time in about two weeks). 
![image](https://user-images.githubusercontent.com/3604963/46480246-74104a00-c7b6-11e8-9eb8-9300e662be37.png)

**Comment by felixse** [comment] 2018-10-05 16:14
I'm suspecting the WebView. We could experiment with [running it in another process](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Controls.WebView#execution-modes), maybe that will help with the leak on closing. But regarding spurlls overnight leaks I have no idea right now.

**Comment by Riebart** [comment] 2018-10-25 01:39
![image](https://user-images.githubusercontent.com/1278193/47470767-c6002a80-d7cc-11e8-8339-34f88e4a7275.png)

I just had this happen to me too. I had exactly one window, with one tab open on one desktop, and it was unresponsive (blue circle spinning). Had to kill it from the Task Manager. This is definitely not related to memory leak on tap open/close.

**Comment by kariudo** [comment] 2019-07-08 14:51
This still seems to be a problem, leaking memory when opening and closing tabs. It is extremely easy to reproduce. Is there no activity on a solution for this?

**Comment by felixse** [comment] 2020-03-03 22:21
This should be fixed by #542 and #548

**Closed by felixse** 2020-03-03 22:21 UTC
Labels: bug
