### ISSUE TITLE
0.1.11.0 crash

### ISSUE THREAD

**Issue by cxfksword** [felixse/FluentTerminal#43] opened 2018-06-17 05:51 UTC
when i start program, wait some seconds will crash, auto close then window. how can i fix it, has some crash log?
![](http://ww1.sinaimg.cn/large/7ce4a9f6gy1fse4ozcgalj20ek0adq5f.jpg)

windows version: 1803

**Comment by felixse** [comment] 2018-06-17 08:17
Can you please open then Windows Event Viewer, go to Windows Logs -> Application, start the app and tell me the error details?

From your screenshot I can tell that both App and SystemTray are working, and a powershell has been created. Does your Powershell work when you start it in its native window?

**Comment by notlmn** [comment] 2018-06-17 09:53
I haven't got time to open an issue but this is the very behavior for me since `0.1.9.0`. Tried all versions and none of them even opened (can get to the settings view and change everything, but the application closes without any output).

The app launches (and closes), there is a tray icon, but there are no events in Event Viewer.

**Comment by felixse** [comment] 2018-06-17 09:58
Did you try with CMD as the default shell? Same behaviour?

**Comment by notlmn** [comment] 2018-06-17 11:14
Tried with CMD, Powershell, and even WSL Bash. Same behavior as above (closes, no events).

**Comment by felixse** [comment] 2018-06-17 12:31
Ok, then I'm out of ideas for know. 
Maybe you can find some time and try to debug it on your machine?

**Comment by notlmn** [comment] 2018-06-18 05:58
Tried uninstalling and reinstalling several times, also tried removing any directory named `FluentTerminal` in `%APPDATA%`.

**Comment by notlmn** [comment] 2018-06-18 06:18
@felixse I know this is out of scope of this issue, but can you provide dependencies and `appx` + cert as separate downloads, it's hard to download 80MB bundle repeatedly while on roaming? (I didn't want to open an issue to ask this.)

**Comment by notlmn** [comment] 2018-06-18 09:13
@felixse The problem got fixed after repeated installations (yes, repeated) of dependency packages and manually installing the cert file multiple times. 🎉🎈

A check for dependencies in the main launcher file?

And regarding package and dependencies, it looks like `appxsym` files are not required for installation (these files make up ~45MB of the total app). If these files are not required then the app would only be ~36MB.

**Comment by felixse** [comment] 2018-06-18 09:53
Nice to hear you got it working 😃 
Nothing we actively do on our side, must be some weird appx installation bug.

appxsym seems to contain debug symbols, I think we can strip that as well for the 'light' download

**Comment by Riebart** [comment] 2018-06-19 19:53
I was able to reproduce it on a brand new install of Windows 10 1803 x64 in a VM, so there's something super weird going on here.

**Comment by felixse** [comment] 2018-06-19 19:57
And you got it running after trying it multiple times?

Tried it myself in a fresh 1803 VM a few days ago, but in my case it installed correctly at first try 😕

**Comment by Riebart** [comment] 2018-06-19 19:59
No, mine refused to run, but I did notice that the x64 2015 UWP runtime failed to install correctly, and installing it from the Dependencies folder didn't work (I had to install it form Powershell with `Add-AppxPackage` as it looked like the install window itself was causing the conflict, which was confusing).

**Comment by cxfksword** [comment] 2018-06-20 06:14
I run `Add-AppDevPackage.ps1` by manual, and it works now.

**Comment by Riebart** [comment] 2018-06-21 21:35
Found it! I think.

This is a bit misleading, and I don't know what exact functionality is causing it, but if you just choose **Sideload Apps** in the Windows 10 developer settings, this is the behaviour you get. If you enable Developer Mode, without reinstalling anything, you get the correct behaviour. Ideally we wouldn't have to enable full-on developer mode to sideload the app, but I don't know what functionality we're using that triggers the issues.

**Comment by felixse** [comment] 2018-06-21 21:55
Can you check whether the loop back exemption is set (you can use this to look it up: https://archive.codeplex.com/?p=loopback) when you are in the ‘crashing state’?

**Comment by Riebart** [comment] 2018-06-22 20:17
Got it:

I have confirmed that running ```CheckNetIsolation LoopbackExempt -a -n="((Get-AppxPackage | where { $_.Name -eq "53621FSApps.FluentTerminal" }).PackageFamilyName)"``` after installing the certificate and `,appxbundle` will fix the crash without requiring that you change the developer settings from "Sideload Apps". You'll need to run the command as administrator, but it will explicitly add the missing loopback permission for only the FluentTerminal app.

**Comment by Riebart** [comment] 2018-06-24 20:14
Sort of the last update I think on this:

I tested this by building it and explicitly revoking the LoopbackExempt status from the development package, and indeed what happens is that the websocket in the JavaScript side times out, and issues a `.onclose()`, which sense `CloseTab` to the terminal bridge.

So this is indeed caused by the same headache that's present in #34 . I'll make a PR that updates the README on how to install to note that if you're sideloading the app, you'll need to run the above PowerShell snippet

**Comment by felixse** [comment] 2018-06-24 20:30
Well, at least we found the issue and also a work around. I would consider this as resolved now, thanks to everyone who contributed here 😃 

The fun continues in #34

**Closed by felixse** 2018-06-24 20:30 UTC

**Comment by corelon** [comment] 2018-09-04 07:52
Hi,
I am having the same issue, and although I followed the various steps above it will not start.
