### ISSUE TITLE
Sudden close of the app

### ISSUE THREAD

**Issue by loox37** [felixse/FluentTerminal#638] opened 2019-12-29 00:12 UTC
The issue happens always when I press the menu button (the three lines on top left).
No idea why.

**Comment by felixse** [comment] 2020-01-05 10:48
What update version of Windows 10 are you using?

**Comment by 0xfiras** [comment] 2020-01-27 12:05
bump.

I am using Windows 10 version 1803

**Comment by felixse** [comment] 2020-02-06 17:23
Ok, then it's a duplicate of #528 and #629

**Closed by felixse** 2020-02-06 17:23 UTC
