### ISSUE TITLE
Bug with the settings

### ISSUE THREAD

**Issue by kiri11-mi1** [felixse/FluentTerminal#877] opened 2020-12-18 07:35 UTC
Faced with such a problem that the application crashes if i press the buttons in the following sequence:
"Settings" - > "Close" - > "Settings".

**Comment by hanskokx** [comment] 2020-12-18 07:37
Can you provide any logs?

**Comment by kiri11-mi1** [comment] 2020-12-18 07:42
> Can you provide any logs?

Unfortunately no, i couldn't find them

**Comment by xylish7** [comment] 2020-12-19 20:53
Have the same problem and the bad part is that you'll lose everything  since the app crashes.😟

**Comment by ZipWin** [comment] 2020-12-23 04:31
I got the same bug, app crashed when I open settings second time.

**Comment by SleepingJempa** [comment] 2020-12-23 22:43
Same for me. I tried to install older releases but nothing changed. App crashed after opening the settings twice.

**Comment by duchess-toffee** [comment] 2021-01-05 08:45
Frequent crashes here just opening and closing settings as well.

**Comment by jareqpl** [comment] 2021-01-10 08:54
@hanskokx 
Hey, i have same issue on windows 10 ver 20H2.
I've found this in event viewer, right after the crash:
`<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-01-10T08:45:05.8271295Z" />
    <EventRecordID>5886</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>DESKTOP-N7V7ITM</Computer>
    <Security />
  </System>
  <EventData>
    <Data>FluentTerminal.App.exe</Data>
    <Data>1.0.0.0</Data>
    <Data>5fb2b21f</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>10.0.19041.662</Data>
    <Data>ec58f015</Data>
    <Data>c000027b</Data>
    <Data>000000000010bd5c</Data>
    <Data>2f78</Data>
    <Data>01d6e72bd28038de</Data>
    <Data>C:\Program Files\WindowsApps\53621FSApps.FluentTerminal_0.7.4.0_x64__87x1pks76srcp\FluentTerminal.App.exe</Data>
    <Data>C:\Windows\System32\KERNELBASE.dll</Data>
    <Data>2df05a62-11c0-4ebf-b1d3-b267c4496488</Data>
    <Data>53621FSApps.FluentTerminal_0.7.4.0_x64__87x1pks76srcp</Data>
    <Data>App</Data>
  </EventData>
</Event>`

**Comment by GitCodeDestroyer** [comment] 2021-01-14 12:23
Only when I open settings second time

**Comment by felixse** [comment] 2021-01-17 10:52
Duplicate of #874 (Fix coming soon)

**Closed by felixse** 2021-01-17 10:52 UTC
