### ISSUE TITLE
背景四角有突兀的白色

### ISSUE THREAD

**Issue by Hovn** [felixse/FluentTerminal#998] opened 2022-02-26 16:05 UTC
例如：
窗口的右键菜单
![image](https://user-images.githubusercontent.com/6801952/155850077-d20256dd-9793-4b76-beb5-43a1b5b81ee8.png)

鼠标在部分地方悬停后出现的提示
![image](https://user-images.githubusercontent.com/6801952/155850055-226f1f22-5614-480c-97d3-e3e5aaf0cb54.png)

**Comment by felixse** [comment] 2022-02-28 18:29
duplicate of https://github.com/felixse/FluentTerminal/issues/532
Updating Windows 10 to a more recent version should fix it

**Closed by felixse** 2022-02-28 18:29 UTC
