### ISSUE TITLE
Feature Request: Mouse Movement Support

### ISSUE THREAD

**Issue by nwhiteman42** [felixse/FluentTerminal#902] opened 2021-03-05 05:06 UTC
I use a terminal editor called micro(https://github.com/zyedidia/micro).  It is essentially nano but you can click around and select with the mouse.  Moving the mouse around does not work with FluentTerminal.  

Here is what I know it works with:
Windows Terminal
WSL Ubuntu
gnome-terminal

**Comment by felixse** [comment] 2021-03-06 12:02
Duplicate of #50

**Closed by felixse** 2021-03-06 12:02 UTC
