### ISSUE TITLE
Selection is not preserved if the "Copy on select" option is enabled

### ISSUE THREAD

**Issue by cimak** [felixse/FluentTerminal#1025] opened 2022-12-06 15:09 UTC
Selection should be preserved when using "Copy on select" - it helps to keep track of where you are/have been on the screen. 

I have a really lengthy log of errors and I'm trying to resolve it one by one: copy file path from log, open it (paste) in the editor, fix it, switch back to the terminal, copy next file path and so on. The problem is that selection is not preserved and I'm losing track of previously copied path

**Comment by felixse** [comment] 2022-12-07 20:51
Duplicate of #569

**Closed by felixse** 2022-12-07 20:51 UTC
Labels: duplicate
