### ISSUE TITLE
Installer won't work on Powershell 6+ (simple fix)

### ISSUE THREAD

**Issue by mikemaccana** [felixse/FluentTerminal#382] opened 2019-05-28 09:46 UTC
When running the install script, it tries to run `$PsHome\PowerShell.exe` which won't exist on Powershell 6:

```
Before installing this app, you need to do the following:
        - Install the signing certificate
Start-Process : This command cannot be run due to the error: The system cannot find the file specified.
At C:\Users\mikem\Downloads\FluentTerminal.App_0.4.1.0_Test\Install.ps1:366 char:25
+ ... inProcess = Start-Process "$PsHome\PowerShell.exe" -Verb RunAs -Argum ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
+ FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand
```

Easily fixed, just use pwsh.exe for Powershell 6 or greater.

**Comment by felixse** [comment] 2019-05-30 09:48
Duplicate of #250 
This should become obsolete by switching to the msi installer

**Comment by mikemaccana** [comment] 2019-05-30 09:54
Thanks Felix! Fluent's still the fastest fully featured terminal for Windows ❤️. When do you think you'll do the next release?

**Comment by felixse** [comment] 2019-05-30 10:16
Just one more resize issue to be fixed. Hopefully this weekend

**Comment by TheZoker** [comment] 2019-06-26 08:46
@felixse Any news on the new release? 😅

**Comment by felixse** [comment] 2019-06-28 05:09
Well, it's too hot on my desk right now, but maybe I'll get to it this weekend 😅

**Comment by mikemaccana** [comment] 2019-07-02 15:11
Massively looking forward to the new one. Windows Terminal is great once you know workarounds for the bugs but Fluent is **way better** out of the box.

**Comment by TheZoker** [comment] 2019-07-03 10:30
@felixse Maybe this weekend? 😅

**Comment by felixse** [comment] 2019-07-03 10:49
It was available yesterday for a short time, but I had to pull it because there was an issue with the package. Will try to fix this today

**Closed** 2020-03-27 11:08 UTC
